# Generated by Django 2.0 on 2017-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20171209_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.SmallIntegerField(default=0)),
                ('sweating', models.SmallIntegerField(default=0)),
                ('vomit', models.SmallIntegerField(default=0)),
                ('muscle_pain', models.SmallIntegerField(default=0)),
                ('diarrhea', models.SmallIntegerField(default=0)),
                ('anemia', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_fever', models.FloatField()),
                ('w_sweating', models.FloatField()),
                ('w_vomit', models.FloatField()),
                ('w_muscle_pain', models.FloatField()),
                ('w_diarrhea', models.FloatField()),
                ('w_anemia', models.FloatField()),
            ],
        ),
    ]
